relativeURLs = true
title = "Flavio Riva"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = ""
    logo = "raoProfilePic2.jpg" 
    
